import { Router } from 'express';
import authRoutes from './auth.js';
import schoolRoutes from './school.js';
import studentRoutes from './students.js';
import feeRoutes from './fees.js';
import publicRoutes from './public.js';
import teacherRoutes from './teachers.js';
import attendanceRoutes from './attendance.js';
import resultRoutes from './results.js';
import inventoryRoutes from './inventory.js';
import disciplineRoutes from './discipline.js';
import parentRoutes from './parents.js';
import settingsRoutes from './settings.js';
import reportRoutes from './reports.js';
import communicationRoutes from './communication.js';
import dashboardRoutes from './dashboard.js';
import locationRoutes from './location.js';
import infrastructureRoutes from './infrastructure.js';
import mediaRoutes from './media.js';
import classRoutes from './classes.js';
import staffRoutes from './staff.js';
import libraryRoutes from './library.js';
import eventRoutes from './events.js';
import { moduleController } from '../controllers/moduleController.js';
import chatRoutes from './chat.js';
import smsRoutes from './sms.js';
import whatsappRoutes from './whatsapp.js';
import onlineClassRoutes from './onlineClasses.js';
import dashboardLayoutRoutes from './dashboardLayouts.js';
import landingMediaRoutes from './landingMedia.js';
import chatGroupRoutes from './chatGroups.js';
import systemMetricsRoutes from './systemMetrics.js';
import admissionRoutes from './admissions.js';
import searchRoutes from './search.js';
import notificationRoutes from './notifications.js';
import adminRoutes from './admin.js';
import usersRoutes from './users.js';
import roleDashboardRoutes from './roleDashboards.js';
import mpesaRoutes from './mpesa.js';
import bursarRoutes from './bursar.js';
import timetableRoutes from './timetable.js';
import storeKeeperRoutes from './storekeeper.js';
import automationRoutes from './automations.js';
import analyticsRoutes from './analytics.js';

const router = Router();

router.use('/', authRoutes);
router.use('/public', publicRoutes);
router.use('/teacher', teacherRoutes);
router.use('/teachers', teacherRoutes);
router.use('/', roleDashboardRoutes);
router.use('/school', schoolRoutes);
router.use('/students', studentRoutes);
router.use('/fees', feeRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/results', resultRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/discipline', disciplineRoutes);
router.use('/parents', parentRoutes);
router.use('/parent', parentRoutes);
router.use('/settings', settingsRoutes);
router.use('/reports', reportRoutes);
router.use('/communication', communicationRoutes);
router.use('/chat', chatRoutes);
router.use('/sms', smsRoutes);
router.use('/whatsapp', whatsappRoutes);
router.use('/online-classes', onlineClassRoutes);
router.use('/dashboard-layouts', dashboardLayoutRoutes);
router.use('/landing-media', landingMediaRoutes);
router.use('/chat-groups', chatGroupRoutes);
router.use('/system-metrics', systemMetricsRoutes);
router.use('/dashboard', dashboardRoutes);
router.get('/modules', moduleController.listAll);
router.use('/location', locationRoutes);
router.use('/infrastructure', infrastructureRoutes);
router.use('/media', mediaRoutes);
router.use('/classes', classRoutes);
router.use('/staff', staffRoutes);
router.use('/library', libraryRoutes);
router.use('/events', eventRoutes);
router.use('/admissions', admissionRoutes);
router.use('/search', searchRoutes);
router.use('/notifications', notificationRoutes);
router.use('/admin', adminRoutes);
router.use('/users', usersRoutes);
router.use('/mpesa', mpesaRoutes);
router.use('/bursar', bursarRoutes);
router.use('/timetable', timetableRoutes);
router.use('/storekeeper', storeKeeperRoutes);
router.use('/automations', automationRoutes);
router.use('/analytics', analyticsRoutes);

export default router;
